[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test_drift_cpi = "7xJ99D8b6LJsbnaqYBgvaa4Ga1nDjfHte3mu3aqS4MYq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/munseon-ug/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
